version: '3.8'

services:
  redis:
    image: redis
    command: redis-server --requirepass Redis2025!
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_container
    restart: always
    ports:
      - "5775:5775/udp"  # For receiving traces in compact thrift protocol
      - "6831:6831/udp"  # For receiving traces in binary thrift protocol
      - "6832:6832/udp"  # For receiving traces in compact thrift protocol
      - "5778:5778"      # For service configuration
      - "16686:16686"    # Jaeger UI
      - "14268:14268"    # API for sending traces
      - "14250:14250"    # GRPC
      - "9411:9411"      # Zipkin compatible endpoint
